{{config(materialized='table',incremental_strategy='merge',unique_key='hash')}}

SELECT BLOCK_HASH, BLOCK_NUMBER, BLOCK_TIMESTAMP, DATE, 
FROM_ADDRESS, GAS, GAS_PRICE, HASH, INPUT, LAST_MODIFIED, 
MAX_FEE_PER_GAS, MAX_PRIORITY_FEE_PER_GAS, NONCE, RECEIPT_CONTRACT_ADDRESS, RECEIPT_CUMULATIVE_GAS_USED, 
RECEIPT_EFFECTIVE_GAS_PRICE, RECEIPT_GAS_USED, RECEIPT_STATUS, TO_ADDRESS, TRANSACTION_INDEX, TRANSACTION_TYPE, VALUE 
FROM
{{ source('ethsnowflake', 'TRANSACTIONS') }}