{{config(materialized='table')}}

SELECT BLOCK_HASH, BLOCK_NUMBER, BLOCK_TIMESTAMP, DATE, 
FROM_ADDRESS, TO_ADDRESS, LAST_MODIFIED, LOG_INDEX, TOKEN_ADDRESS, TRANSACTION_HASH, VALUE
FROM {{ source('ethsnowflake', 'TOKEN_TRANSFERS') }}